FROM python:3.8.10
FROM continuumio/anaconda3

ENV PYTHONUNBUFFERED 1
RUN mkdir /code
WORKDIR /code
COPY requirements.txt /code/
RUN conda install -y -c conda-forge vaex

# RUN pip install -r requirements.txt
COPY . /code/